### ISSUE TITLE
DOI - Change DOI query API to use query params

### ISSUE THREAD

**Issue by dvstans** [jfharney/ScientificWorkspace#27]
Instead of encoding DOI number in path, use a query param such as: /path?doi=/10.111/OLCF/12345

**Comment by markdcarringer** [comment]
Right now, I have it set for DOI names in this format: 

09.2815/4539580

because that is what we are getting in Dev. However, when we move to production, we are going to have to change it to accept DOI names like this one: 

10.2815/OLCF/4539580

The reason this difference matters is because calls to our proxy layer interpret a URL with a DOI name with two slashes as syntactically distinct from a DOI name with only one slash. 

As far as the change goes, Doug has successfully updated his service to accept a new format of URL. However, the URL actually looks like this: 

https://doi1.ccs.ornl.gov/doi/json?doi=10.111/OLCF/12345

You know, I just remembered how to fix this...

**Comment by fullerdj** [comment]
The infix (/OLCF/) is entirely optional and up to local sites to determine. This is a policy discussion we should have at the appropriate level to determine what (if any) text to include.
